const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let token='',pid='',data=null,current=null,review=null,outputReview=null,polling=false,pending=null,timeline=[],timelineDirty=false,timelineBaseRevision=0,noteDirty=false,editorSnapshot=null;
function message(s){$('#message').textContent=s;}
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-Studio-Token':token},body:JSON.stringify(body)}:{});const j=await r.json();if(!r.ok)throw Error(j.error||'요청에 실패했습니다.');return j;}
function error(e){message(e.message);if($('#editor').open){let s=$('#editor-status');if(!s){s=document.createElement('p');s.id='editor-status';s.setAttribute('role','status');s.className='warning';$('#cut-story').before(s);}s.textContent=e.message;}}
function documentHtml(text){return String(text||'').split('\n').map(line=>/^#{1,4} /.test(line)?'<h3>'+esc(line.replace(/^#+ /,''))+'</h3>':line?'<p'+(line.startsWith('- ')?' class="bullet"':'')+'>'+esc(line.replace(/^- /,''))+'</p>':'').join('');}
function storyHtml(c){return c.story?.length?c.story.map(s=>`<article class="scenario"><p class="hint">컷 ${esc(s.id)} · ${esc(s.target)}</p><dl><dt>대사 · 말투</dt><dd>${esc(s.dialogue)}</dd><dt>행동</dt><dd>${esc(s.action)}</dd><dt>카메라 · 연결</dt><dd>${esc(s.camera)}</dd></dl></article>`).join(''):'<p class="hint">대화로 장면 구성을 정하면 여기에 표시됩니다.</p>';}
function imageFigure(src,label){return `<figure><figcaption>${esc(label)}</figcaption>${src?`<a href="${esc(src)}" target="_blank" rel="noopener"><img loading="lazy" src="${esc(src)}" alt="${esc(label)}"></a>`:'<div class="empty-frame">이미지 준비 전</div>'}</figure>`;}
function frameURL(source,index){return '/api/frame-image?project='+encodeURIComponent(pid)+'&path='+encodeURIComponent(source)+'&frame='+index;}
function fillProjects(projects){$('#projects').innerHTML=projects.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');$('#projects').value=pid;}
async function boot(){const b=await api('/api/bootstrap');token=b.token;const requested=new URLSearchParams(location.search).get('project')||localStorage.getItem('studio-project');pid=b.projects.some(p=>p.id===requested)?requested:(b.projects[0]?.id||'');fillProjects(b.projects);if(pid)await refresh(true);else{$('#title').textContent='새 이야기의 시작';$('#subtitle').textContent='Codex에 새 프로젝트의 주제와 등장인물을 말해주세요.';$('#cuts').innerHTML='<div class="empty-state">대화에서 프로젝트와 컷을 만들면 이곳에 자동으로 나타납니다.</div>';}}
async function refresh(force=false){const selected=pid;if(!selected)return;const fresh=await api('/api/project?id='+encodeURIComponent(selected));if(pid!==selected)return;if(!force&&data?.revision===fresh.revision)return;if($('#editor').open){pending=fresh;return;}data=fresh;render();}
function render(){if(!data)return;$('#title').textContent=data.name;$('#subtitle').textContent='대화에서 만든 컷과 결과를 자동으로 불러옵니다.';$('#docs').innerHTML=data.docs.map(d=>`<a target="_blank" rel="noopener" href="${esc(d.url)}">${esc(d.name)} ↗</a>`).join('');const generated=data.cuts.filter(c=>c.video),saved=generated.filter(c=>c.trim&&!c.trim_stale);$('#stats').innerHTML=`<span><b>${data.cuts.length}</b> 계획 컷</span><span><b>${generated.length}</b> 생성 영상</span><span><b>${saved.length}</b> 구간 저장</span><span class="sync">● 자동 동기화</span>`;$('#brief-content').innerHTML=documentHtml(data.story?.brief);$('#script-content').textContent=data.story?.script||'촬영 대본 준비 전';renderCards();if(!timelineDirty){timeline=[...(data.timeline??generated.map(c=>c.id))];timelineBaseRevision=data.timeline_revision;}renderTimeline();renderExports();renderFinalOutput();window.renderProductionAssets?.();}
function renderCards(){const q=$('#search').value.toLowerCase();const rows=data.cuts.filter(c=>(c.id+' '+c.name).toLowerCase().includes(q));$('#cuts').innerHTML=rows.map(c=>{const start=c.planned_start||c.original_image||c.image,end=c.planned_end||c.end;return `<article class="card"><div class="card-top"><span class="cut-id">CUT ${esc(c.id)}</span><span class="status ${c.video?'ready':''}">${c.video?(c.trim_stale?'원본 변경':c.trim?'구간 저장됨':'영상 검수 가능'):'제작 준비'}</span></div><button class="card-media" data-open="${esc(c.id)}" aria-label="${esc(c.name)} 컷 열기"><div>${start?`<img loading="lazy" src="${esc(start)}" alt="시작 이미지">`:'<span>시작 이미지<br>준비 전</span>'}<small>${c.planned_start?'시작 계획':'시작 입력'}</small></div><div>${end?`<img loading="lazy" src="${esc(end)}" alt="종료 이미지">`:'<span>종료 이미지<br>준비 전</span>'}<small>${c.planned_end?'종료 계획':'실제 종료'}</small></div></button><div class="card-body"><h3>${esc(c.name)}</h3><p class="dialogue-snippet">${esc(c.story?.map(s=>s.dialogue).join(' / ')||'대사와 장면 구성 준비 전')}</p><div class="card-bottom"><span>${c.duration!=null?c.duration.toFixed(3)+'초':'영상 생성 전'}</span><button data-open="${esc(c.id)}">${c.video?'영상 · 구간 선택':'구성 보기'} ↗</button></div></div></article>`;}).join('')||'<div class="empty-state">등록된 컷이 없습니다. 대화로 컷을 만들면 자동으로 표시됩니다.</div>';$('#cuts').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openCut(b.dataset.open));}
function openCut(id){$('#editor-status')?.remove();const c=data.cuts.find(c=>c.id===id);if(!c)return;current=id;editorSnapshot=structuredClone(c);noteDirty=false;$('#cut-title').textContent=c.name;$('#cut-label').textContent='CUT '+c.id+' / REVIEW';$('#note').value=c.note;$('#cut-story').innerHTML=storyHtml(c);$('#prompt').textContent=typeof c.prompt==='string'?c.prompt:JSON.stringify(c.prompt,null,2);$('#model').textContent=c.model||'';$('#planned-frames').innerHTML=imageFigure(c.planned_start||c.image,'시작 계획 / 선택 후보')+imageFigure(c.planned_end,'종료 계획');$('#image-status').textContent='계획 이미지는 다음 생성 후보이며 실제 영상의 시작·종료와 다를 수 있습니다.';$('#cut-frames').innerHTML=c.video?'':imageFigure(c.planned_start||c.image,'시작 계획')+imageFigure(c.planned_end,'종료 계획');renderVersions(c);$('#preview').innerHTML=c.video?`<video controls playsinline preload="metadata" poster="${esc(c.original_image||c.image||'')}" src="${esc(c.video)}"></video>`:c.image?`<img src="${esc(c.image)}" alt="${esc(c.name)} 계획 이미지">`:'<div class="empty-state">영상 생성 전<br>대화에서 제작을 진행하면 이곳에 나타납니다.</div>';$('#review-controls').innerHTML='';$('#editor').showModal();if(c.video){const thisProject=pid;review=new FrameReview($('#preview video'),$('#review-controls'),{project:thisProject,path:c.source_path,trim:c.trim,revision:c.trim_revision,cut:c.id,editable:true,onSave:async(payload)=>{const result=await api('/api/trim',{project:thisProject,cut:c.id,...payload});if(editorSnapshot?.id===c.id){editorSnapshot.trim=payload;editorSnapshot.trim_revision=result.revision;}message('사용 구간을 저장했습니다. 편집 목록에 반영됩니다.');pending=await api('/api/project?id='+encodeURIComponent(thisProject));return result;},onReady:info=>{if(current!==id||!$('#editor').open)return;$('#cut-frames').innerHTML=imageFigure(frameURL(c.source_path,0),'영상 실제 첫 프레임')+imageFigure(c.end||frameURL(c.source_path,info.count-1),'영상 실제 마지막 프레임');}});}}
function closeEditor(){if((review?.dirty||noteDirty)&&!window.confirm('아직 저장하지 않은 구간이나 메모가 있어요. 저장하지 않고 닫을까요?'))return;$('#editor').close();}
$('#editor').addEventListener('cancel',e=>{e.preventDefault();closeEditor();});$('#close').onclick=closeEditor;$('#editor').addEventListener('close',()=>{review?.destroy();review=null;$('#preview').innerHTML='';$('#review-controls').innerHTML='';current=null;editorSnapshot=null;noteDirty=false;if(pending){data=pending;pending=null;render();}else refresh().catch(error);});$('#note').oninput=()=>{noteDirty=true;};
async function edit(body){try{await api('/api/edit',{project:pid,cut:current,...body});const fresh=await api('/api/project?id='+encodeURIComponent(pid));pending=fresh;editorSnapshot={...editorSnapshot,...fresh.cuts.find(c=>c.id===current)};renderVersions(editorSnapshot);message('저장했습니다.');return true;}catch(e){error(e);return false;}}
$('#save-note').onclick=async()=>{if(await edit({action:'note',note:$('#note').value}))noteDirty=false;};
function renderVersions(c){$('#versions').innerHTML='<div class="versions">'+c.versions.map((v,i)=>`<button data-version="${esc(v.id)}" aria-pressed="${v.id===c.selected}"><img src="${esc(v.url)}" alt="이미지 후보 ${i+1}">후보 ${i+1}</button>`).join('')+'</div>'+(c.selected?'<button id="clear-selection">후보 선택 해제</button>':'');$('#versions').querySelectorAll('[data-version]').forEach(b=>b.onclick=()=>edit({action:'select',version:b.dataset.version}));if($('#clear-selection'))$('#clear-selection').onclick=()=>edit({action:'select',version:null});}
async function upload(file){if(!file)return;if(file.size>20*1024*1024)return error(Error('이미지는 20MB 이하로 선택해 주세요.'));try{const bytes=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});await edit({action:'upload',name:file.name,bytes});}catch(e){error(e);}}
$('#upload').onchange=e=>{upload(e.target.files[0]);e.target.value='';};$('#drop').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#upload').click();}};$('#drop').ondragover=e=>e.preventDefault();$('#drop').ondrop=e=>{e.preventDefault();upload(e.dataTransfer.files[0]);};
function renderLibrary(){const q=$('#library-search').value.toLowerCase();$('#library-grid').innerHTML=data.library.filter(x=>x.path.toLowerCase().includes(q)).map(x=>`<button data-path="${esc(x.path)}"><img loading="lazy" src="${esc(x.url)}" alt="${esc(x.name)}"><span>${esc(x.name)}</span></button>`).join('');$('#library-grid').querySelectorAll('[data-path]').forEach(b=>b.onclick=async()=>{$('#library').close();await edit({action:'existing',path:b.dataset.path});});}
$('#library-open').onclick=()=>{renderLibrary();$('#library').showModal();};$('#library-close').onclick=()=>$('#library').close();$('#library-search').oninput=renderLibrary;
function renderTimeline(){const generated=data.cuts.filter(c=>c.video),ordered=[...timeline.map(id=>generated.find(c=>c.id===id)).filter(Boolean),...generated.filter(c=>!timeline.includes(c.id))];let ready=0;$('#timeline').innerHTML=ordered.map(c=>{const included=timeline.includes(c.id),i=timeline.indexOf(c.id),good=c.trim&&!c.trim_stale;if(included&&good)ready++;return `<div class="timeline-row ${included?'included':''}"><label><input type="checkbox" data-include="${esc(c.id)}" ${included?'checked':''}><span class="cut-id">${esc(c.id)}</span> ${esc(c.name)}</label><span class="trim-summary">${c.trim_stale?'원본 변경 · 다시 선택':good?`${c.trim.in_frame+1}~${c.trim.out_frame} 프레임 선택`:'사용 구간 미저장'}</span><div><button data-review="${esc(c.id)}">구간 ${good?'수정':'선택'}</button><button data-move="${esc(c.id)}" data-delta="-1" aria-label="${esc(c.name)} 위로" ${!included||i===0?'disabled':''}>↑</button><button data-move="${esc(c.id)}" data-delta="1" aria-label="${esc(c.name)} 아래로" ${!included||i===timeline.length-1?'disabled':''}>↓</button></div></div>`;}).join('')||'<div class="empty-state">영상이 생성되면 편집 목록이 나타납니다.</div>';$('#assembly-summary').textContent=`${timeline.length}개 컷 포함 · ${ready}개 구간 저장 완료`;const running=data.jobs.some(j=>['queued','running'].includes(j.status));$('#export').disabled=!timeline.length||ready!==timeline.length||timelineDirty||!data.timeline||running;$('#save-timeline').disabled=running||!generated.length;$('#timeline-status').textContent=timelineDirty?'목록 변경됨 · 저장해 주세요':!data.timeline?'편집 목록을 먼저 저장해 주세요':ready!==timeline.length?'포함한 모든 컷의 사용 구간을 저장해 주세요':'저장된 구간으로 출력할 준비가 됐어요.';$('#timeline').querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>openCut(b.dataset.review));$('#timeline').querySelectorAll('[data-include]').forEach(b=>b.onchange=()=>{if(b.checked)timeline.push(b.dataset.include);else timeline=timeline.filter(id=>id!==b.dataset.include);timelineDirty=true;renderTimeline();});$('#timeline').querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const i=timeline.indexOf(b.dataset.move),j=i+Number(b.dataset.delta);[timeline[i],timeline[j]]=[timeline[j],timeline[i]];timelineDirty=true;renderTimeline();});}
$('#save-timeline').onclick=async()=>{try{await api('/api/timeline',{project:pid,cuts:timeline,revision:timelineBaseRevision});timelineDirty=false;await refresh(true);message('편집 순서와 포함할 컷을 저장했습니다.');}catch(e){error(e);}};
$('#export').onclick=async()=>{const button=$('#export');button.disabled=true;try{await api('/api/export',{project:pid});await refresh(true);message('원본 연결본과 편집 연결본을 만들고 있습니다. 완료되면 아래에 나타납니다.');}catch(e){error(e);renderTimeline();}};
async function openOutputFolder(path,button){button.disabled=true;try{await api('/api/open-output-folder',{project:pid,path});message('저장 폴더를 열었습니다.');}catch(e){error(e);}finally{button.disabled=false;}}
function renderFinalOutput(){const box=$('#final-output');box.hidden=!data.full;if(!data.full){box.innerHTML='';return;}box.innerHTML=`<div class="section-heading"><div><p class="eyebrow">FINAL EDIT</p><h2>최종 편집 완성본</h2><p class="hint">${Number(data.seconds||0).toFixed(3)}초 · 현재 프로젝트의 전체 영상</p></div><div class="final-actions"><button id="watch-final" class="primary">완성본 재생</button><button id="folder-final">저장 폴더 열기</button><a href="${esc(data.full)}" download="final-edit.mp4">영상 저장</a></div></div>`;$('#watch-final').onclick=()=>showOutput({url:data.full,path:data.full_path,duration:data.seconds},'최종 편집 완성본');$('#folder-final').onclick=e=>openOutputFolder(data.full_path,e.currentTarget);}
function showOutput(output,label){outputReview?.destroy();$('#output-title').textContent=label+' · '+Number(output.duration).toFixed(3)+'초';const video=$('#full-player');video.src=output.url;$('#player-dialog').showModal();outputReview=new FrameReview(video,$('#output-review'),{project:pid,path:output.path,editable:false});}
function renderExports(){$('#exports').innerHTML=data.jobs.map(j=>`<article class="export-card"><div><h3>${j.status==='complete'?'원본과 편집본':j.status==='error'?'출력 중단':esc(j.stage)}</h3><p class="hint">${new Date(j.created_at*1000).toLocaleString('ko-KR')}</p>${j.error?`<p class="warning">${esc(j.error)}</p>`:''}</div><div class="export-pair">${Object.entries(j.outputs).map(([mode,o])=>`<div><b>${mode==='raw'?'원본 전체':'편집본'} · ${o.duration.toFixed(3)}초</b><button data-output="${esc(j.id)}" data-mode="${mode}">재생 · 프레임 확인 ↗</button><a href="${esc(o.url)}" download="${mode}.mp4">영상 저장</a><button data-folder="${esc(o.path)}">저장 폴더 열기</button></div>`).join('')}</div></article>`).join('')||'<div class="empty-state">사용 구간을 저장한 뒤 이어붙이기를 누르면 두 영상이 여기에 쌓입니다.</div>';$('#exports').querySelectorAll('[data-output]').forEach(b=>b.onclick=()=>openOutput(b.dataset.output,b.dataset.mode));$('#exports').querySelectorAll('[data-folder]').forEach(b=>b.onclick=()=>openOutputFolder(b.dataset.folder,b));}
function openOutput(id,mode){const output=data.jobs.find(j=>j.id===id)?.outputs[mode];if(output)showOutput(output,mode==='raw'?'원본 전체':'편집본');}
$('#player-close').onclick=()=>$('#player-dialog').close();$('#player-dialog').addEventListener('close',()=>{outputReview?.destroy();outputReview=null;$('#full-player').pause();$('#full-player').removeAttribute('src');$('#full-player').load();});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{['overview','characters','board','assembly','feedback'].forEach(id=>$('#'+id).hidden=id!==b.dataset.view);document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});
$('#projects').onchange=async()=>{if((timelineDirty||window.assetsDirty?.())&&!window.confirm('저장하지 않은 편집 목록이 있어요. 프로젝트를 바꿀까요?')){$('#projects').value=pid;return;}pid=$('#projects').value;localStorage.setItem('studio-project',pid);history.replaceState(null,'','?project='+encodeURIComponent(pid));data=null;timelineDirty=false;pending=null;window.resetLessonMemory?.();try{await refresh(true);}catch(e){error(e);}};
$('#search').oninput=()=>data&&renderCards();$('#refresh').onclick=()=>refresh(true).then(()=>message('최신 프로젝트를 불러왔습니다.')).catch(error);
window.addEventListener('beforeunload',e=>{if(review?.dirty||noteDirty||timelineDirty||window.assetsDirty?.()){e.preventDefault();e.returnValue='';}});
setInterval(async()=>{if(polling||document.hidden)return;polling=true;try{const b=await api('/api/bootstrap');token=b.token;fillProjects(b.projects);if(!pid&&b.projects.length){pid=b.projects[0].id;fillProjects(b.projects);}await refresh();}catch(e){message('자동 동기화 연결을 확인하고 있어요. '+e.message);}finally{polling=false;}},3000);
boot().catch(error);

/* Project character bible and reusable production notebook. */
const productionTags=['기획','인물','카메라','연기','연속성','사운드','프롬프트','검수','작업방식'];
const kindNames={sheet:'인물시트',reference:'참고 사진',detail:'상세 이미지'};
const characterStates={draft:'설정 초안',reference:'참고 기준',approved:'확정 기준'};
const feedbackStates={open:'반영할 내용',applied:'반영함',archived:'보관'};
const feedbackOrigins={user:'사용자 피드백',review:'결과 검수',reference:'참고 자료'};
let characterEdit=null,feedbackEdit=null,characterDirty=false,feedbackDirty=false,assetBusy=false;
window.assetsDirty=()=>characterDirty||feedbackDirty||assetBusy;
function assetFields(row){return ['description','appearance','wardrobe','performance','continuity'].map((k,i)=>row[k]?`<div><dt>${['인물 소개','외형 기준','복장 · 소품','말투 · 연기','유지할 특징'][i]}</dt><dd>${esc(row[k])}</dd></div>`:'').join('');}
function assetImage(im){return `<figure><a href="${esc(im.url)}" target="_blank" rel="noopener"><img loading="lazy" src="${esc(im.url)}" alt="${esc(im.label||kindNames[im.kind])}"></a><figcaption>${esc(kindNames[im.kind]||'참고 이미지')} · ${esc(im.label)}</figcaption></figure>`;}
function feedbackCard(row,shared=false){return `<article class="feedback-card"><div class="note-meta"><span>${esc(feedbackOrigins[row.origin]||'기록')}</span><span>${esc(feedbackStates[row.status]||'반영할 내용')}</span></div><h4>${esc(row.title)}</h4><p>${esc(row.observation)}</p><div class="next-action"><b>다음에 할 일</b><p>${esc(row.action)}</p></div>${row.context?`<p class="hint"><b>적용 조건</b> ${esc(row.context)}</p>`:''}<div class="note-tags">${(row.tags||[]).map(t=>`<span>${esc(t)}</span>`).join('')}</div>${row.evidence?`<p class="hint">근거 · ${esc(row.evidence)}</p>`:''}${row.source?`<p class="hint">출처 · ${esc(row.source)}</p>`:''}<div class="note-footer">${shared?`<a href="/?project=${encodeURIComponent(row.project_id)}&view=feedback">${esc(row.project_name)} ↗</a>`:`<span>${row.scope==='reusable'?'다음 작품에도 참고':'이 작품에서만'}</span><button data-feedback-edit="${esc(row.id)}">수정</button>`}</div></article>`;}
function matchesFeedback(row){const q=$('#feedback-search').value.trim().toLowerCase(),tag=$('#feedback-tag').value;return (!q||[row.title,row.observation,row.action,row.context,...(row.tags||[])].join(' ').toLowerCase().includes(q))&&(!tag||row.tags?.includes(tag));}
window.renderProductionAssets=function(){
 if(!data)return;
 const available=Boolean(data.characters&&data.feedback);
 $('#add-character').disabled=!available;$('#add-feedback').disabled=!available;
 if(!available){const pending='<div class="empty-state">제작실 서버를 다시 시작하면 인물·피드백 기능을 사용할 수 있어요.<br>기존 프로젝트와 영상은 그대로 보존되어 있습니다.</div>';$('#character-list').innerHTML=pending;$('#feedback-list').innerHTML=pending;$('#lesson-list').innerHTML='';return;}
 const people=data.characters?.items||[];
 $('#character-list').innerHTML=people.map(c=>`<article class="character-card"><div class="character-art">${c.images?.length?assetImage(c.images.find(i=>i.kind==='sheet')||c.images[0]):'<div class="empty-state">인물시트 준비 전<br>설명을 먼저 정하고 이미지를 추가해 주세요.</div>'}</div><div class="character-copy"><div class="note-meta"><span>${esc(c.role||'역할 미정')}</span><span>${esc(characterStates[c.status])}</span></div><h3>${esc(c.name)}</h3><dl>${assetFields(c)}</dl><p class="hint">출처 · ${esc(c.source||'미등록')}</p><div class="note-footer"><span>${c.images?.length||0}개 이미지</span><button data-character-edit="${esc(c.id)}">설명 · 시트 관리</button></div>${c.images?.length>1?`<details><summary>모든 시트와 참고 이미지</summary><div class="attachment-grid">${c.images.map(assetImage).join('')}</div></details>`:''}</div></article>`).join('')||'<div class="empty-state">아직 등록된 인물이 없어요.<br>인물 추가에서 이름과 역할을 정하고, 시트나 참고 사진을 모아보세요.</div>';
 $('#character-list').querySelectorAll('[data-character-edit]').forEach(b=>b.onclick=()=>openCharacter(b.dataset.characterEdit));
 const notes=(data.feedback?.items||[]).filter(matchesFeedback);
 $('#feedback-count').textContent=`${notes.length}개`;
 $('#feedback-list').innerHTML=notes.map(r=>feedbackCard(r)).join('')||'<div class="empty-state">조건에 맞는 피드백이 없어요.<br>고칠 점과 다음 행동을 함께 기록해 보세요.</div>';
 $('#feedback-list').querySelectorAll('[data-feedback-edit]').forEach(b=>b.onclick=()=>openFeedback(b.dataset.feedbackEdit));
 window.renderLessonMemory?.();
 $('#cut-note-list').innerHTML=data.cuts.filter(c=>c.note?.trim()).map(c=>`<article class="cut-note"><b>CUT ${esc(c.id)} · ${esc(c.name)}</b><p>${esc(c.note)}</p><button data-note-promote="${esc(c.id)}">피드백으로 정리</button></article>`).join('')||'<p class="hint">컷 검수 화면에서 저장한 메모가 여기에 표시됩니다.</p>';
 $('#cut-note-list').querySelectorAll('[data-note-promote]').forEach(b=>b.onclick=()=>{const c=data.cuts.find(c=>c.id===b.dataset.notePromote);openFeedback(null,{title:`${c.name} 검토`,observation:c.note,evidence:`CUT ${c.id}`,source:'컷 검수 메모',scope:'project'});});
 $('#prompt-guide').innerHTML=documentHtml(data.prompt_guide||'작성 양식 준비 전');
};
function putForm(form,row){for(const e of form.elements){if(e.name&&e.type!=='checkbox')e.value=row[e.name]??'';}}
function readForm(form){return Object.fromEntries(new FormData(form).entries());}
function fillCharacterImages(){const row=data.characters?.items.find(c=>c.id===characterEdit?.id);$('#character-images').innerHTML=(row?.images||[]).map(assetImage).join('')||'<p class="hint">등록된 이미지가 없어요.</p>';$('#character-upload').disabled=!row||assetBusy;}
function openCharacter(id){const row=data.characters?.items.find(c=>c.id===id)||{id:crypto.randomUUID(),status:'draft',images:[]};characterEdit={...structuredClone(row),project:pid,revision:data.characters?.revision||0};putForm($('#character-form'),row);$('#character-form-status').textContent='';$('#character-dialog-title').textContent=id?row.name+' · 인물 기준':'새 인물';characterDirty=false;fillCharacterImages();$('#character-dialog').showModal();}
function openFeedback(id,initial={}){const row=data.feedback?.items.find(c=>c.id===id)||{id:crypto.randomUUID(),origin:'user',scope:'project',status:'open',tags:[],...initial};feedbackEdit={...structuredClone(row),project:pid,revision:data.feedback?.revision||0};putForm($('#feedback-form'),row);window.fillLessonMetadata?.(row);$('#feedback-tags').querySelectorAll('input').forEach(x=>x.checked=row.tags?.includes(x.value));$('#feedback-form-status').textContent='';feedbackDirty=false;$('#feedback-dialog').showModal();}
function closeWorkspace(id){if(assetBusy)return;const dirty=id==='character-dialog'?characterDirty:feedbackDirty;if(dirty&&!confirm('저장하지 않은 내용이 있어요. 닫을까요?'))return;$('#'+id).close();}
document.querySelectorAll('[data-close-workspace]').forEach(b=>b.onclick=()=>closeWorkspace(b.dataset.closeWorkspace));
for(const id of ['character-dialog','feedback-dialog']){$('#'+id).addEventListener('cancel',e=>{e.preventDefault();closeWorkspace(id);});$('#'+id).addEventListener('close',()=>{if(id==='character-dialog')characterDirty=false;else feedbackDirty=false;});}
$('#add-character').onclick=()=>data&&openCharacter();$('#add-feedback').onclick=()=>data&&openFeedback();
$('#character-form').oninput=()=>characterDirty=true;$('#feedback-form').oninput=()=>feedbackDirty=true;
$('#character-form').onsubmit=async e=>{e.preventDefault();if(assetBusy)return;assetBusy=true;const button=e.submitter;button.disabled=true;try{const item={...characterEdit,...readForm(e.target)};delete item.project;delete item.revision;const result=await api('/api/characters',{project:characterEdit.project,item,revision:characterEdit.revision});characterEdit={...item,project:characterEdit.project,revision:result.revision};characterDirty=false;await refresh(true);fillCharacterImages();$('#character-form-status').textContent='저장했어요. 아래에서 시트를 추가할 수 있어요.';}catch(err){$('#character-form-status').textContent=err.message;}finally{assetBusy=false;button.disabled=false;fillCharacterImages();}};
$('#feedback-form').onsubmit=async e=>{e.preventDefault();if(assetBusy)return;assetBusy=true;e.submitter.disabled=true;try{const item={...feedbackEdit,...readForm(e.target),tags:[...$('#feedback-tags').querySelectorAll('input:checked')].map(x=>x.value)};delete item.project;delete item.revision;window.applyYoutubeRetrospective?.(item);window.readLessonMetadata?.(item);await api('/api/feedback',{project:feedbackEdit.project,item,revision:feedbackEdit.revision});feedbackDirty=false;$('#feedback-dialog').close();await refresh(true);message('피드백을 저장했어요. 참고 범위에 따라 다음 프로젝트에도 표시됩니다.');}catch(err){$('#feedback-form-status').textContent=err.message;}finally{assetBusy=false;e.submitter.disabled=false;}};
$('#character-upload').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file||assetBusy)return;if(characterDirty){$('#character-form-status').textContent='인물 설명을 먼저 저장한 뒤 이미지를 추가해 주세요.';return;}if(file.size>20*1024*1024){$('#character-form-status').textContent='이미지는 최대 20MB입니다.';return;}assetBusy=true;fillCharacterImages();try{const bytes=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});const result=await api('/api/characters',{action:'upload',project:characterEdit.project,id:characterEdit.id,revision:characterEdit.revision,name:file.name,bytes,label:$('#character-image-label').value||file.name,kind:$('#character-image-kind').value});characterEdit.revision=result.revision;characterEdit.images=result.items.find(c=>c.id===characterEdit.id).images;await refresh(true);$('#character-form-status').textContent='시트·참고 이미지를 추가했어요.';}catch(err){$('#character-form-status').textContent=err.message;}finally{assetBusy=false;fillCharacterImages();}};
$('#feedback-tag').insertAdjacentHTML('beforeend',productionTags.map(t=>`<option>${t}</option>`).join(''));
$('#feedback-tags').insertAdjacentHTML('beforeend',productionTags.map(t=>`<label><input type="checkbox" value="${t}"> ${t}</label>`).join(''));
$('#feedback-search').oninput=window.renderProductionAssets;$('#feedback-tag').onchange=window.renderProductionAssets;
const initialView=new URLSearchParams(location.search).get('view');
if(['characters','feedback','overview','board','assembly'].includes(initialView))document.querySelector(`[data-view="${initialView}"]`).click();
if(data)window.renderProductionAssets();
