class FrameReview {
  constructor(video,box,options){this.video=video;this.box=box;this.options=options;this.dirty=false;this.alive=true;this.index=0;this.callback=null;this.revision=options.revision||0;this.abort=new AbortController();this.load();}
  async load(){
    this.box.innerHTML='<p class="hint">원본의 실제 프레임 시각을 읽고 있어요…</p>';
    try{const r=await fetch('/api/frames?project='+encodeURIComponent(this.options.project)+'&path='+encodeURIComponent(this.options.path),{signal:this.abort.signal});const info=await r.json();if(!r.ok)throw Error(info.error);if(!this.alive)return;this.info=info;
      const saved=this.options.trim,valid=saved&&saved.source_sha256===info.sha256&&saved.in_frame>=0&&saved.out_frame<=info.count&&saved.in_frame<saved.out_frame;
      this.inFrame=valid?saved.in_frame:0;this.outFrame=valid?saved.out_frame:info.count;
      this.box.innerHTML=`<div class="frame-review"><div class="clock-line"><output data-ui="clock">0.000초</output><span data-ui="frame"></span></div><input class="frame-slider" aria-label="영상 프레임 위치" data-ui="slider" type="range" min="0" max="${info.count-1}" step="1" value="0"><div class="review-buttons"><button data-action="prev" aria-label="이전 프레임">◀ 1프레임</button><button data-action="play">재생 / 정지</button><button data-action="next" aria-label="다음 프레임">1프레임 ▶</button></div><div class="seek-row"><label>이동할 시간 <input data-ui="seconds" aria-label="이동할 초" type="number" min="${info.start}" max="${info.end}" step="0.001" value="${info.start.toFixed(3)}"></label><button data-action="seek">이동</button><label>속도 <select data-ui="speed"><option value="1">1배속</option><option value="0.5">0.5배속</option><option value="0.25">0.25배속</option></select></label></div>${this.options.editable?'<div class="mark-buttons"><button data-action="in">여기부터 사용</button><button data-action="out">이 프레임까지 사용</button><button data-action="all">전체 구간</button></div><div class="selection"><b data-ui="selection"></b><small data-ui="selection-detail"></small></div><div class="review-buttons"><button data-action="range">선택 구간 재생</button><button data-action="save" class="primary">사용 구간 저장</button></div>':''}<p class="hint" data-ui="status" role="status"></p></div>`;
      this.ui=name=>this.box.querySelector(`[data-ui="${name}"]`);this.button=name=>this.box.querySelector(`[data-action="${name}"]`);
      this.button('prev').onclick=()=>this.seek(this.index-1);this.button('next').onclick=()=>this.seek(this.index+1);this.button('play').onclick=()=>{this.rangePlay=false;this.video.paused?this.video.play().catch(e=>this.status(e.message)):this.video.pause();};
      this.button('seek').onclick=()=>{const value=Number(this.ui('seconds').value);if(!Number.isFinite(value)||value<info.start||value>info.end)return this.status('영상 범위 안의 시각을 입력해 주세요.');this.seek(this.at(value));};
      this.ui('slider').oninput=e=>this.seek(Number(e.target.value));this.ui('speed').onchange=e=>this.video.playbackRate=Number(e.target.value);
      if(this.options.editable){this.button('in').onclick=()=>{if(this.index>=this.outFrame)return this.status('시작점은 종료점보다 앞이어야 합니다.');this.inFrame=this.index;this.changed();};this.button('out').onclick=()=>{if(this.index<this.inFrame)return this.status('종료점은 시작점보다 앞일 수 없습니다.');this.outFrame=this.index+1;this.changed();};this.button('all').onclick=()=>{this.inFrame=0;this.outFrame=info.count;this.changed();};this.button('save').onclick=()=>this.save();this.button('range').onclick=async()=>{this.seek(this.inFrame);this.rangePlay=true;try{await this.video.play();}catch(e){this.status(e.message);}};this.selection();}
      this.onTime=()=>this.display(this.video.currentTime);this.video.addEventListener('timeupdate',this.onTime);this.video.addEventListener('seeked',this.onTime);
      if(this.video.requestVideoFrameCallback){const tick=(_,metadata)=>{if(!this.alive)return;this.display(metadata.mediaTime);this.callback=this.video.requestVideoFrameCallback(tick);};this.callback=this.video.requestVideoFrameCallback(tick);}
      this.display(info.start);this.status(saved&&!valid?'원본이 바뀌었어요. 사용 구간을 다시 확인하고 저장해 주세요.':valid?'저장된 구간을 불러왔습니다.':this.options.editable?'전체 구간이 표시되어 있어요. 원하는 구간을 선택하고 저장하세요.':'실제 원본의 프레임 시각을 표시합니다.');this.options.onReady?.(info);
    }catch(e){if(this.alive)this.box.textContent='프레임 정보를 읽지 못했습니다. '+e.message;}
  }
  at(t){let lo=0,hi=this.info.count;while(lo<hi){const m=(lo+hi)>>1;if(this.info.frames[m]<=t+0.00001)lo=m+1;else hi=m;}return Math.max(0,lo-1);}
  endTime(){return this.outFrame===this.info.count?this.info.end:this.info.frames[this.outFrame];}
  display(t){if(!this.alive||!this.ui)return;this.index=this.at(t);this.ui('clock').textContent=this.info.frames[this.index].toFixed(3)+'초';this.ui('frame').textContent=`${this.index+1} / ${this.info.count} 프레임`;this.ui('slider').value=this.index;if(document.activeElement!==this.ui('seconds'))this.ui('seconds').value=this.info.frames[this.index].toFixed(3);if(this.rangePlay&&(t>=this.endTime()-0.001||this.video.ended)){this.rangePlay=false;this.video.pause();this.seek(this.outFrame-1);}}
  seek(index){if(!this.info)return;this.rangePlay=false;this.video.pause();index=Math.max(0,Math.min(this.info.count-1,index));const t=this.info.frames[index],next=this.info.frames[index+1]??this.info.end;this.index=index;this.video.currentTime=t+Math.min(0.001,(next-t)/4);this.display(t);}
  changed(){this.dirty=true;this.selection();this.status('구간 변경됨 · 저장해 주세요.');this.options.onDirty?.();}
  selection(){const begin=this.info.frames[this.inFrame],end=this.endTime();this.ui('selection').textContent=`${begin.toFixed(3)} → ${end.toFixed(3)}초 · ${(end-begin).toFixed(3)}초 사용`;this.ui('selection-detail').textContent=`${this.inFrame+1}~${this.outFrame}번째 프레임 포함 · ${this.outFrame-this.inFrame}프레임. 종료 시각은 다음 프레임 경계입니다.`;}
  status(text){if(this.alive&&this.ui)this.ui('status').textContent=text;}
  async save(){if(this.saving)return;this.saving=true;this.button('save').disabled=true;const a=this.inFrame,b=this.outFrame;try{const result=await this.options.onSave({source_sha256:this.info.sha256,in_frame:a,out_frame:b,revision:this.revision});if(!this.alive)return;this.revision=result.revision;this.dirty=this.inFrame!==a||this.outFrame!==b;this.status(this.dirty?'이전 선택 저장 완료. 새 변경도 저장해 주세요.':'사용 구간 저장 완료');}catch(e){this.status(e.message);}finally{this.saving=false;if(this.alive)this.button('save').disabled=false;}}
  destroy(){this.alive=false;this.abort.abort();this.video.pause();if(this.callback!=null)this.video.cancelVideoFrameCallback?.(this.callback);if(this.onTime){this.video.removeEventListener('timeupdate',this.onTime);this.video.removeEventListener('seeked',this.onTime);}}
}
